### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by LucyFann** [jokieleung/NTRD#10]
Hi jokie,
first of all, thanks for your work!
1. The results of Dist@N and R@N of KGSF reported in the NTRD are different from those reported in the KGSF itself. Is this because you and KGSF use different evaluation scripts? I read some recent CRS papers(NTRD, KGSF, Revcore, C2CRS), and the results have some inconsistencies with each other.  However, the evaluation formulas are all fixed, so I'm very confused at this point. Are these inconsistent results because of different evaluation scripts used by these baselines?
2. I also want to know how did you calculate the "item ratio and item diversity" in your evaluation script. 
Thanks a lot! Lucy

**Comment by Yang-bug-star** [comment]
Hi，did you solve the problem? Could you tell me how ReR metric can be done in KGSF?

**Comment by LucyFann** [comment]
I have not solved this yet. I think ReR(in NTRD) is a little different from Recall@k in KGSF. Since NTRD changes the switching network. NTRD calculate the top-k (k=10, k=50) items of the probability distribution for this position contain the ground truth item. You can refer to this with their original paper in section 5.2.

**Comment by Yang-bug-star** [comment]
but KGSF did not consider recommedation recall in response,so how can rer@k be measured in KGSF. And I'm always confused about the function of recommender module in KGSF. I think it just can fine-tune the knowledge representations of entity and concepts but the recommended items themself are useless since the final recommended items given to the client is controlled totally by the generation module.
